export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";

export const CLEAN_NEW_PROPERTY = "DELETE_NEW_PROPERTY";
export const ADD_NEW_PROPERTY = "ADD_NEW_PROPERTY";
export const ERROR_ADD_NEW_PROPERTY = "ERROR_ADD_NEW_PROPERTY";
export const LOADING_NEW_PROPERTY = "LOADING_NEW_PROPERTY";

export const CLEAN_NEW_PLACES = "DELETE_NEW_PLACES";
export const ADD_NEW_PLACES = "ADD_NEW_PLACES";
export const ERROR_ADD_NEW_PLACES = "ERROR_ADD_NEW_PLACES";
export const LOADING_NEW_PLACES = "LOADING_NEW_PLACES";
export const GET_PLACES = "GET_PLACES";

export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_SUCCESSFULL_USER = "LOGIN_SUCCESSFULL_USER";
export const LOGIN_ERROR_USER = "LOGIN_ERROR_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOADING_USER = "LOADING_USER";

export const ADD_PLACE = "ADD_PLACE"
