export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const GET_FAVORITES = "GET_FAVORITES";
export const SELECTED_FAVORITE = "SELECTED_FAVORITE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";

export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_USER = "LOGIN_USER";
